### ISSUE TITLE
Damage Log avatar has disappeared

### ISSUE THREAD

**Issue by cs96and** [ZeroXNoxus/smaller-chat-5e#1]
Hi, author of Damage Log module here!

It looks like you have completely hidden the avatar in the Damage Log entries in the latest version.  I'm just wondering why you have done this?  Would it be possible to re-enable them, or make it configurable whether to hide them or not please?

Thanks.

**Comment by ZeroXNoxus** [comment]
Hi, thank you for the issue!

First of all; thank you for creating Damage Log! It has been a really useful module for us during our sessions!

I have hidden the avatar because the avatar seems broken in my chat log, I suppose the issue is caused by another module? I'm uncertain if you've seen this issue before, but this breaks the damage log to a certain extend and makes it very unintuitive, so I've decided to hide the avatar for now:

![image](https://github.com/user-attachments/assets/74561775-ca6d-47c4-b204-2c3fa373d1ed)
 
Any idea why this issue occurs?

**Comment by cs96and** [comment]
https://github.com/cs96and/FoundryVTT-damage-log/issues/47

Do you have the ModuleManagement+ module installed?  If so, try disabling that.  ModuleManagement+ seems abandoned, so I didn't try to fix it in Damage Log.

**Comment by ZeroXNoxus** [comment]
Ah, alright, I'll add a bit of script to add a class to the DOM if MM+ is enabled and this should resolve the issue.
